```{r}
models <- c("~1","~region","~scale_averagewater","~scale_averagewater+scale_averagewater2","~scale_short","~scale_short+scale_short2","~scale_int","~scale_int+scale_int2","~region+scale_averagewater-1","~region+scale_short","~region+scale_int","~scale_averagewater+scale_short","~scale_averagewater+scale_averagewater2+scale_short","~scale_averagewater+scale_short+scale_short2","~scale_averagewater+scale_int","~scale_averagewater+scale_averagewater2+scale_int","~scale_averagewater+scale_int+scale_int2","~scale_short+scale_int","~scale_short+scale_short2+scale_int","~scale_short+scale_int+scale_int2")


library(unmarked)


sora <- read.csv('~/data/2015_sora.csv', header=T)

cov <- read.csv('~/data/2015_cov.csv', header=T)

sora <- sora[order(sora$impound),]
cov <- cov[order(cov$impound),]

cov$scale_short2 <- cov$scale_short^2
cov$scale_int2 <- cov$scale_int^2
cov$scale_averagewater2 <- cov$scale_averagewater^2

sora <- sora[,2:31]
cutpt = as.numeric(c(0,1,2,3,4,5)) 

umf = unmarkedFrameGDS(y=sora, 
                       numPrimary=6,
                       siteCovs = cov,
                       survey="line", 
                       dist.breaks=cutpt,  
                       unitsIn="m", 
                       tlength=cov$length
)
```

```{r}

model <- list()



for(i in 1:length(models)){
model[[models[[i]]]] = gdistsamp(lambdaformula = as.formula(models[i]), 
                       phiformula = ~1, 
                       pformula = ~1,
                       data = umf, keyfun = "hazard", mixture="NB",se = T, output="abund")
}

```

```{r}
model$global <- gdistsamp(lambdaformula = ~scale_short+scale_averagewater+region+scale_int+scale_pe, 
                      phiformula = ~1, 
                      pformula = ~ 1,
                      data = umf, keyfun = "hazard", mixture="NB",se = T, output="abund")
```
```{r}
save(model, file="~/unmarked/2015_models.Rdata")
list  = fitList(model)
model = modSel(list)
model
```