---
output: html_document
---

```{r}
library(unmarked)

fitstats <- function(fm) {
  observed <- getY(fm@data)
  expected <- fitted(fm)
  resids <- residuals(fm)
  sse <- sum(resids^2)
  chisq <- sum((observed - expected)^2 / expected)
  freeTuke <- sum((sqrt(observed) - sqrt(expected))^2)
  out <- c(SSE=sse, Chisq=chisq, freemanTukey=freeTuke)
  return(out)
}

load("~/unmarked/2012_global_model.Rdata")

summary(global)

global <- gdistsamp(lambdaformula = ~scale_short+scale_averagewater+scale_int, 
                          phiformula = ~1, 
                          pformula = ~ 1,
                          data = umf, keyfun = "hazard", mixture="NB",se = T, output="abund")


par12 <- parboot(global, statistic=fitstats, nsim=10) ## still errors out

hist(par12@t.star)
```

```{r}

load("~/unmarked/2013_global_model.Rdata")

summary(global)

#par13 <- parboot(global, statistic=fitstats, nsim=1) ## still errors out

#hist(par13@t.star)
```

```{r}

load("~/unmarked/2014_global_model.Rdata")

summary(global)

#par14 <- parboot(global, statistic=fitstats, nsim=1) ## still errors out

#hist(par14@t.star)

```